version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "8084:8084"
    volumes:
        - .:/app
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: movieapp_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
    - "5432:5432"
volumes:
  postgres_data: